routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/

include_once('admin_routes.php');

include_once('front_routes.php');

app/Models/Settings.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Settings extends Model {

	protected $table = 'settings';

	public $timestamps = false;

	public function group(){
		return $this->belongsTo('App\Models\SettingsGroup','settings_group_id');
	}

	public function subgroup(){
		return $this->belongsTo('App\Models\SettingsGroup','settings_subgroup_id');
	}

	public function language(){
		return $this->hasMany('App\Models\SettingsLanguage','settings_id');
	}

	public static function getByGroup($symbol){
		$rows = self::whereHas('group',function($query) use($symbol){
			$query->where('symbol','=',$symbol);
		})->get();
		return self::parse($rows);
	}

	public static function getBySymbol($symbol){
		if(self::checkIfExists($symbol)){
			$row = self::where('symbol','=',strtolower($symbol))->first();
			return $row->value;
		}else{
			return "";
		}
	}

	public static function checkIfExists($symbol){
		return self::where('symbol','=',strtolower($symbol))->count() > 0;
	}

	public function getOptionsAttribute($value)
  {
        return json_decode($value);
  }

	public static function getAll($languageSymbol = false){
		$rows = self::with('language')
						->orderBy('settings_group_id','ASC')
						->orderBy('position','ASC')
						->get();
		return self::parse($rows,$languageSymbol);
	}

	public static function parse($rows,$languageSymbol = false){
		$response = [];
		foreach($rows as $row){
			if(count($row->language)>0){
				if($languageSymbol != false){
					foreach($row->language as $l){
						if($l->language->symbol == $languageSymbol)
							$response[$row->symbol] = $l->value;
					}
				}else{
					$response[$row->symbol] = $row;
				}
			}else
				$response[$row->symbol] = $row->value;
		}
		return $response;
	}

	public function saveSettings($data){
			try{
				$symbols = self::pluck('symbol');

				foreach($symbols as $symbol){
					if(array_key_exists($symbol,$data)){
						$value = $data[$symbol];

						if(is_array($value)){
								$languageSettings = self::with('language')->where('symbol','=',$symbol)->first();
								if($languageSettings->language->count()>0){
									\App\Models\SettingsLanguage::where('settings_id','=',$languageSettings->id)->delete();
								}
								foreach($value as $languageId => $set){
										\App\Models\SettingsLanguage::insert([
											'language_id' => $languageId,
											'value' => $set,
											'settings_id' => $languageSettings->id
										]);
								}
						}else{
							self::where('symbol','=',$symbol)->update(['value'=>$value]);
						}
					}
				}

				if(array_key_exists('contact_name',$data)){
					$model = new \App\Models\OpeningHours();
					$model->store($data);
				}

				return true;
			}catch(Exception $e){
				return false;
			}
	}

}

app/Http/Controllers/Admin/SettingsController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Models\SettingsGroup;

class SettingsController extends AdminController
{
    public function __construct(){
    	parent::__construct();
      $this->middleware('privilege:settings');
      $this->setActiveMenu(['settings']);
    }

    public function index(){
      $this->setBreadcrumbs('settings');
      $model = new \App\Models\SettingsGroup();
      return view('admin.settings.index')->with([
        'header' => trans('menu.settings'),
        'list' => $model->getAll(),
        'langs' => \App\Models\Language::getActive(),
        'openinghours' => \App\Models\OpeningHours::all()
      ]);
    }

    public function save(Request $request){
      $model = new \App\Models\Settings();
      $result = $model->saveSettings($request->input());
      return $this->setMessageBoxAfterRedirect((int)$result, route('settings'), 'admin.update_'.($result ? 'success' : 'failure'));
    }
}

resources/views/admin/settings/tabs/analytics.blade.php
@include('admin.settings.tab')

resources/views/admin/settings/tabs/contact.blade.php
<form action="" method="post" data-formvalidation novalidate="" id="contactSettingsForm" class="contactTab">
  <div class="contactTab__row contactTab__row--title">
    <div class="contactTab__col">
      <div class="contactTab__name">{{trans('admin.category.basic_data')}}</div>
    </div>
    <div class="contactTab__col">
      <div class="contactTab__row contactTab__row--Vcenter">
      <div class="contactTab__name">{{trans('admin.openinghours.header')}}</div>
        <button type="button" class="button button--small button--green button--withIcon button--iconAdd" data-openinghours-add>{{trans('admin.openinghours.add_button')}}</button>
      </div>
    </div>
  </div>
  <div class="contactTab__row">
    <div class="contactTab__col">
      @foreach($group as $set)
        <div class="contactTab__row contactTab__row--form">
          <div class="contactTab__col4">
            <label class="tabsForm__label" for="{{$set->symbol}}">{{trans($set->name)}}</label>
          </div>
          <div class="contactTab__col8 inputBlock">
            @if($set->type=="text")
              <input type="text" class="inputBlock__field" name="{{$set->symbol}}" value="{{$set->value}}" id="{{$set->symbol}}" @if($set->placeholder!="") placeholder="{{trans($set->placeholder)}}" @endif>
            @elseif($set->type=="number")
              <input type="number" class="inputBlock__field" name="{{$set->symbol}}" value="{{$set->value}}" id="{{$set->symbol}}" min="0" >
            @elseif($set->type=="email")
              <input type="email" class="inputBlock__field" name="{{$set->symbol}}" value="{{$set->value}}" id="{{$set->symbol}}" @if($set->placeholder!="") placeholder="{{trans($set->placeholder)}}" @endif>
            @elseif($set->type=="textarea")
              <textarea class="inputBlock__textarea" name="{{$set->symbol}}" id="{{$set->symbol}}" @if($set->placeholder!="") placeholder="{{trans($set->placeholder)}}" @endif>{{$set->value}}</textarea>
            @elseif($set->type=="radio")
              @foreach($set->options as $key=>$value)
                <div class="inputBlock__checkbox"><input type="radio"
                  @if($key==$set->value)
                    checked
                  @endif
                  name="{{$set->symbol}}" id="{{$set->symbol}}" value="{{$key}}"><label class="inputBlock__checkboxText" for="{{$set->symbol}}"><i></i><span>{{trans($value)}}</span></label></div>
              @endforeach
            @elseif($set->type=="checkbox")
              <div class="inputBlock__checkbox">
                <input type="hidden" name="{{$set->symbol}}" value="0"/>
                <input type="checkbox" name="{{$set->symbol}}" value="1"
                @if($set->value==1)
                  checked
                @endif
                id="{{$set->symbol}}" />
                <label class="inputBlock__checkboxText" for="{{$set->symbol}}"><i></i><span></span></label>
              </div>
            @endif
          </div>
        </div>
      @endforeach

    </div>
    <div class="contactTab__col">

          <div class="" data-openinghours-box data-list-sortable="openinghours" data-list-sortablenoajax>
            @if(isset($openinghours) && count($openinghours) > 0)
              @foreach($openinghours as $term)
                {!!View::make('admin.settings.partial.openinghours',['term' => $term,'langs'=>$langs])->render()!!}
              @endforeach
            @endif
          </div>

    </div>
  </div>
  @include('admin.partial.form.save',['cancel_url'=>route('settings')])
</form>

<div data-select-noBind data-openinghours-template class="hidden">
  <?php unset($term); ?>
  @include('admin.settings.partial.openinghours')
</div>

resources/views/admin/settings/tabs/images.blade.php
<form action="" method="post" id="imagesSettingsForm" class="imagesTab">

  <?php $subgroup_id = 0; $col_index = 0; ?>

  @foreach($group as $set)
    @if($subgroup_id!=$set->settings_subgroup_id)
        @if($subgroup_id != 0)
              </div> {{-- panel body --}}
            </div> {{-- panel --}}
          </div> {{-- col-md-6 --}}

          @if($col_index % 2 == 0 && $col_index!=0)
            </div> {{-- row --}}
          @endif
        @endif

      @if($col_index % 2 == 0 )
        <div class="row">
      @endif

        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading tabsForm__label">{{trans($set->subgroup->name)}}</div>
            <div class="panel-body form-group">

      <?php
        $col_index++;
        $subgroup_id = $set->settings_subgroup_id;
      ?>
    @endif

    <div class="row">
      <div class="col-lg-9">
        <label class="tabsForm__label tabsForm__label--small" for="{{$set->symbol}}">{{trans($set->name)}}</label>
      </div>
      <div class="col-lg-3">
        <input type="number" class="inputBlock__field required" name="{{$set->symbol}}"
            @if($set->placeholder!="") {{trans($set->placeholder)}} @endif
            data-formvalidation-label = "{{trans($set->subgroup->name)}} {{lcfirst(trans($set->name))}}"
            value="{{$set->value}}" id="{{$set->symbol}}" min="0">
      </div>
    </div>

  @endforeach

</div> {{-- panel body --}}
</div> {{-- panel --}}
</div> {{-- col-md-6 --}}
</div> {{-- row --}}


  @include('admin.partial.form.save',['cancel_url'=>route('settings')])
</form>

resources/views/admin/settings/tabs/mail.blade.php
@include('admin.settings.tab')

resources/views/admin/settings/tabs/map.blade.php
@include('admin.settings.tab')

resources/views/admin/settings/tabs/meta_tag.blade.php
<form action="" method="post" id="metaSettingsForm" class="tabsForm">
  @foreach($group as $set)
    <div class="tabsForm__row">
        @if($set->type=="text")
          @include('admin.partial.lang.input',[
            'label' => trans($set->name),
            'field' => 'value',
            'field_name' => $set->symbol,
            'required' => true,
            'variable' => 'set',
            'mypage' => 'settings'
          ])
        @endif
    </div>
  @endforeach

  @include('admin.partial.form.save',['cancel_url'=>route('settings')])
</form>

resources/views/admin/settings/tabs/other.blade.php
@include('admin.settings.tab')

resources/views/admin/settings/tabs/social_media.blade.php
@include('admin.settings.tab')

resources/views/admin/settings/tabs/videos.blade.php
<form action="" method="post" id="settingsVideoForm" class="imagesTab">

  <?php $subgroup_id = 0; $col_index = 0; ?>

  @foreach($group as $set)
    @if($subgroup_id!=$set->settings_subgroup_id)
        @if($subgroup_id != 0)
              </div> {{-- panel body --}}
            </div> {{-- panel --}}
          </div> {{-- col-md-6 --}}

          @if($col_index % 2 == 0 && $col_index!=0)
            </div> {{-- row --}}
          @endif
        @endif

      @if($col_index % 2 == 0 )
        <div class="row">
      @endif

        <div class="col-md-6">
          <div class="panel panel-default">
            <div class="panel-heading tabsForm__label">{{trans($set->subgroup->name)}}</div>
            <div class="panel-body form-group">

      <?php
        $col_index++;
        $subgroup_id = $set->settings_subgroup_id;
      ?>
    @endif

    <div class="row">
      <div class="col-lg-9">
        <label class="tabsForm__label tabsForm__label--small" for="{{$set->symbol}}">{{trans($set->name)}}</label>
      </div>
      <div class="col-lg-3">
        <input type="number" class="inputBlock__field required" name="{{$set->symbol}}"
          @if($set->placeholder!="") {{trans($set->placeholder)}} @endif
          data-formvalidation-label = "{{trans($set->subgroup->name)}} {{lcfirst(trans($set->name))}}"
          value="{{$set->value}}" id="{{$set->symbol}}" min="0">
      </div>
    </div>

  @endforeach

</div> {{-- panel body --}}
</div> {{-- panel --}}
</div> {{-- col-md-6 --}}
</div> {{-- row --}}

  @include('admin.partial.form.save',['cancel_url'=>route('settings')])
</form>